# 1.1 Imports

In [2]:
import pandas as pd
import numpy as np
import re
import requests
from collections import Counter

# 1.2 Load the data

In [4]:
df = pd.read_csv('../data/raw/PhiUSIIL_Phishing_URL_Dataset.csv')
df.head()

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,...,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,...,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,...,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,...,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,...,1,0,1,244,15,34,72,1,85,1

# 1.3 Dataset overview

In [6]:
df.describe()

,URLLength,DomainLength,IsDomainIP,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,TLDLength,NoOfSubDomain,HasObfuscation,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
count,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,...,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000
mean,34.573095,21.470396,0.002706,78.430778,0.845508,0.260423,0.055747,2.764456,1.164758,0.002057,...,0.237007,0.023474,0.486775,26.075689,6.333111,10.522305,65.071113,2.377629,49.262516,0.571895
std,41.314153,9.150793,0.051946,28.976055,0.216632,0.251628,0.010587,0.599739,0.600969,0.045306,...,0.425247,0.151403,0.499826,79.411815,74.866296,22.312192,176.687539,17.641097,161.027430,0.494805
min,13.000000,4.000000,0.000000,0.155574,0.000000,0.000000,0.001083,2.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,23.000000,16.000000,0.000000,57.024793,0.680000,0.005977,0.050747,2.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
50%,27.000000,20.000000,0.000000,100.000000,1.000000,0.079963,0.057970,3.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,8.000000,2.000000,6.000000,12.000000,0.000000,10.000000,1.000000
75%,34.000000,24.000000,0.000000,100.000000,1.000000,0.522907,0.062875,3.000000,1.000000,0.000000,...,0.000000,0.000000,1.000000,29.000000,8.000000,15.000000,88.000000,1.000000,57.000000,1.000000
max,6097.000000,110.000000,1.000000,100.000000,1.000000,0.522907,0.090824,13.000000,10.000000,1.000000,...,1.000000,1.000000,1.000000,8956.000000,35820.000000,6957.000000,27397.000000,4887.000000,27516.000000,1.000000

In [7]:
df.dtypes

FILENAME                       object
URL                            object
URLLength                       int64
Domain                         object
DomainLength                    int64
IsDomainIP                      int64
TLD                            object
URLSimilarityIndex            float64
CharContinuationRate          float64
TLDLegitimateProb             float64
URLCharProb                   float64
TLDLength                       int64
NoOfSubDomain                   int64
HasObfuscation                  int64
NoOfObfuscatedChar              int64
ObfuscationRatio              float64
NoOfLettersInURL                int64
LetterRatioInURL              float64
NoOfDegitsInURL                 int64
DegitRatioInURL               float64
NoOfEqualsInURL                 int64
NoOfQMarkInURL                  int64
NoOfAmpersandInURL              int64
NoOfOtherSpecialCharsInURL      int64
SpacialCharRatioInURL         float64
IsHTTPS                         int64
LineOfCode                      int64
LargestLineLength               int64
HasTitle                        int64
Title                          object
DomainTitleMatchScore         float64
URLTitleMatchScore            float64
HasFavicon                      int64
Robots                          int64
IsResponsive                    int64
NoOfURLRedirect                 int64
NoOfSelfRedirect                int64
HasDescription                  int64
NoOfPopup                       int64
NoOfiFrame                      int64
HasExternalFormSubmit           int64
HasSocialNet                    int64
HasSubmitButton                 int64
HasHiddenFields                 int64
HasPasswordField                int64
Bank                            int64
Pay                             int64
Crypto                          int64
HasCopyrightInfo                int64
NoOfImage                       int64
NoOfCSS                         int64
NoOfJS                          int64
NoOfSelfRef                     int64
NoOfEmptyRef                    int64
NoOfExternalRef                 int64
label                           int64
dtype: object

In [8]:
df.isnull().sum()

FILENAME                      0
URL                           0
URLLength                     0
Domain                        0
DomainLength                  0
IsDomainIP                    0
TLD                           0
URLSimilarityIndex            0
CharContinuationRate          0
TLDLegitimateProb             0
URLCharProb                   0
TLDLength                     0
NoOfSubDomain                 0
HasObfuscation                0
NoOfObfuscatedChar            0
ObfuscationRatio              0
NoOfLettersInURL              0
LetterRatioInURL              0
NoOfDegitsInURL               0
DegitRatioInURL               0
NoOfEqualsInURL               0
NoOfQMarkInURL                0
NoOfAmpersandInURL            0
NoOfOtherSpecialCharsInURL    0
SpacialCharRatioInURL         0
IsHTTPS                       0
LineOfCode                    0
LargestLineLength             0
HasTitle                      0
Title                         0
DomainTitleMatchScore         0
URLTitleMatchScore            0
HasFavicon                    0
Robots                        0
IsResponsive                  0
NoOfURLRedirect               0
NoOfSelfRedirect              0
HasDescription                0
NoOfPopup                     0
NoOfiFrame                    0
HasExternalFormSubmit         0
HasSocialNet                  0
HasSubmitButton               0
HasHiddenFields               0
HasPasswordField              0
Bank                          0
Pay                           0
Crypto                        0
HasCopyrightInfo              0
NoOfImage                     0
NoOfCSS                       0
NoOfJS                        0
NoOfSelfRef                   0
NoOfEmptyRef                  0
NoOfExternalRef               0
label                         0
dtype: int64

In [9]:
df.columns

Index(['FILENAME', 'URL', 'URLLength', 'Domain', 'DomainLength', 'IsDomainIP',
       'TLD', 'URLSimilarityIndex', 'CharContinuationRate',
       'TLDLegitimateProb', 'URLCharProb', 'TLDLength', 'NoOfSubDomain',
       'HasObfuscation', 'NoOfObfuscatedChar', 'ObfuscationRatio',
       'NoOfLettersInURL', 'LetterRatioInURL', 'NoOfDegitsInURL',
       'DegitRatioInURL', 'NoOfEqualsInURL', 'NoOfQMarkInURL',
       'NoOfAmpersandInURL', 'NoOfOtherSpecialCharsInURL',
       'SpacialCharRatioInURL', 'IsHTTPS', 'LineOfCode', 'LargestLineLength',
       'HasTitle', 'Title', 'DomainTitleMatchScore', 'URLTitleMatchScore',
       'HasFavicon', 'Robots', 'IsResponsive', 'NoOfURLRedirect',
       'NoOfSelfRedirect', 'HasDescription', 'NoOfPopup', 'NoOfiFrame',
       'HasExternalFormSubmit', 'HasSocialNet', 'HasSubmitButton',
       'HasHiddenFields', 'HasPasswordField', 'Bank', 'Pay', 'Crypto',
       'HasCopyrightInfo', 'NoOfImage', 'NoOfCSS', 'NoOfJS', 'NoOfSelfRef',
       'NoOfEmptyRef', 'NoOfExternalRef', 'label'],
      dtype='object')

In [10]:
df.shape

(235795, 56)

# 1.4 Exploring for non-ASCII characters

But first, we can safely drop the FILENAME features as it's content is not relevant to our present study.

In [13]:
df.drop(columns=['FILENAME'], inplace=True)

# 1.4.1 URL

In [15]:
def contains_foreign_characters(url):
    '''A function to find out urls with non-ASCII characters'''
    return bool(re.search(r'[^\x00-\x7F]', url))

In [16]:
df['url_contains_foreign'] = df['URL'].apply(contains_foreign_characters)

In [17]:
df[df['url_contains_foreign'] == True]

,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,...,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label,url_contains_foreign
127839,https://22017-5502.s3.webspace.re/privatkunden...,128,22017-5502.s3.webspace.re,25,0,re,7.650119,0.636364,0.000094,0.048575,...,0,0,0,1,0,2,0,0,0,True
158380,https://vinted.6545657.xyz/p5ci5kt9Ã¢â‚¬â€¹Ã¢â...,65,vinted.6545657.xyz,18,0,xyz,12.652169,1.000000,0.001750,0.030235,...,0,0,0,0,0,0,0,0,0,True

There are only two urls that contains non-ASCII characters. We can drop these rows as their percentage is negligible, less than 1%.

In [19]:
df.drop(index=[127839, 158380], inplace=True)

# 1.4.2 Domain

In [21]:
df['domain_contains_foreign'] = df['Domain'].apply(contains_foreign_characters)

In [22]:
df[df['domain_contains_foreign'] == True]

Empty DataFrame
Columns: [URL, URLLength, Domain, DomainLength, IsDomainIP, TLD, URLSimilarityIndex, CharContinuationRate, TLDLegitimateProb, URLCharProb, TLDLength, NoOfSubDomain, HasObfuscation, NoOfObfuscatedChar, ObfuscationRatio, NoOfLettersInURL, LetterRatioInURL, NoOfDegitsInURL, DegitRatioInURL, NoOfEqualsInURL, NoOfQMarkInURL, NoOfAmpersandInURL, NoOfOtherSpecialCharsInURL, SpacialCharRatioInURL, IsHTTPS, LineOfCode, LargestLineLength, HasTitle, Title, DomainTitleMatchScore, URLTitleMatchScore, HasFavicon, Robots, IsResponsive, NoOfURLRedirect, NoOfSelfRedirect, HasDescription, NoOfPopup, NoOfiFrame, HasExternalFormSubmit, HasSocialNet, HasSubmitButton, HasHiddenFields, HasPasswordField, Bank, Pay, Crypto, HasCopyrightInfo, NoOfImage, NoOfCSS, NoOfJS, NoOfSelfRef, NoOfEmptyRef, NoOfExternalRef, label, url_contains_foreign, domain_contains_foreign]
Index: []

[0 rows x 57 columns]

# 1.4.3 TLD

In [24]:
df['tld_contains_foreign'] = df['TLD'].apply(contains_foreign_characters)

In [25]:
df[df['tld_contains_foreign'] == True]

Empty DataFrame
Columns: [URL, URLLength, Domain, DomainLength, IsDomainIP, TLD, URLSimilarityIndex, CharContinuationRate, TLDLegitimateProb, URLCharProb, TLDLength, NoOfSubDomain, HasObfuscation, NoOfObfuscatedChar, ObfuscationRatio, NoOfLettersInURL, LetterRatioInURL, NoOfDegitsInURL, DegitRatioInURL, NoOfEqualsInURL, NoOfQMarkInURL, NoOfAmpersandInURL, NoOfOtherSpecialCharsInURL, SpacialCharRatioInURL, IsHTTPS, LineOfCode, LargestLineLength, HasTitle, Title, DomainTitleMatchScore, URLTitleMatchScore, HasFavicon, Robots, IsResponsive, NoOfURLRedirect, NoOfSelfRedirect, HasDescription, NoOfPopup, NoOfiFrame, HasExternalFormSubmit, HasSocialNet, HasSubmitButton, HasHiddenFields, HasPasswordField, Bank, Pay, Crypto, HasCopyrightInfo, NoOfImage, NoOfCSS, NoOfJS, NoOfSelfRef, NoOfEmptyRef, NoOfExternalRef, label, url_contains_foreign, domain_contains_foreign, tld_contains_foreign]
Index: []

[0 rows x 58 columns]

# 1.4.4 Title

In [27]:
df['title_contains_foreign'] = df['Title'].apply(contains_foreign_characters)

In [28]:
df[df['title_contains_foreign'] == True]

,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,...,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label,url_contains_foreign,domain_contains_foreign,tld_contains_foreign,title_contains_foreign
0,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,0.061933,...,20,28,119,0,124,1,False,False,False,True
1,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,0.050207,...,9,8,39,0,217,1,False,False,False,True
4,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,0.059441,...,15,34,72,1,85,1,False,False,False,True
10,https://www.religionenlibertad.com,33,www.religionenlibertad.com,26,0,com,100.0,1.000000,0.522907,0.063946,...,13,10,376,1,9,1,False,False,False,True
23,https://www.diariodealmeria.es,29,www.diariodealmeria.es,22,0,es,100.0,1.000000,0.006411,0.068406,...,4,10,609,12,93,1,False,False,False,True
24,https://www.town.minamichita.lg.jp,33,www.town.minamichita.lg.jp,26,0,jp,100.0,0.631579,0.023045,0.054906,...,10,21,2,0,7,1,False,False,False,True
33,https://www.bikeseoul.com,24,www.bikeseoul.com,17,0,com,100.0,1.000000,0.522907,0.062645,...,29,17,49,0,13,1,False,False,False,True

In [29]:
title_foreign = df[df['title_contains_foreign'] == True]

In [30]:
title_foreign[['Title']]

                                                Title
0   à¸‚à¹ˆà¸²à¸§à¸ªà¸” à¸‚à¹ˆà¸²à¸§à¸§à¸±à¸™à¸™à¸µ...
1               johannes gutenberg-universitÃ¤t mainz
4                      fundaciÃ³n rewilding argentina
10      religiÃ³n en libertad | noticias de religiÃ³n
23             diario de almeria - diario de almerÃ­a
24               å—çŸ¥å¤šç”ºå…¬å¼ã‚¦ã‚§ãƒ–ã‚µã‚¤ãƒˆ
33  ì„œìš¸ìžì „ê±° ë”°ë¦‰ì´ - ë¬´ì¸ëŒ€ì—¬ì‹œìŠ¤í…œ

We can safely drop these rows because there percentage is also pretty low under 1%.

In [32]:
df.drop(df[df['title_contains_foreign'] == True].index, inplace=True)

In [33]:
df[df['title_contains_foreign'] == True]

Empty DataFrame
Columns: [URL, URLLength, Domain, DomainLength, IsDomainIP, TLD, URLSimilarityIndex, CharContinuationRate, TLDLegitimateProb, URLCharProb, TLDLength, NoOfSubDomain, HasObfuscation, NoOfObfuscatedChar, ObfuscationRatio, NoOfLettersInURL, LetterRatioInURL, NoOfDegitsInURL, DegitRatioInURL, NoOfEqualsInURL, NoOfQMarkInURL, NoOfAmpersandInURL, NoOfOtherSpecialCharsInURL, SpacialCharRatioInURL, IsHTTPS, LineOfCode, LargestLineLength, HasTitle, Title, DomainTitleMatchScore, URLTitleMatchScore, HasFavicon, Robots, IsResponsive, NoOfURLRedirect, NoOfSelfRedirect, HasDescription, NoOfPopup, NoOfiFrame, HasExternalFormSubmit, HasSocialNet, HasSubmitButton, HasHiddenFields, HasPasswordField, Bank, Pay, Crypto, HasCopyrightInfo, NoOfImage, NoOfCSS, NoOfJS, NoOfSelfRef, NoOfEmptyRef, NoOfExternalRef, label, url_contains_foreign, domain_contains_foreign, tld_contains_foreign, title_contains_foreign]
Index: []

[0 rows x 59 columns]

Now we can safely remove the extra columns startinf from 'url_contains_foreign'

In [35]:
col_index = df.columns.get_loc('url_contains_foreign')
col_to_delete = df.columns[col_index:]
df.drop(columns=col_to_delete)

,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
2,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.000000,0.866667,0.028555,0.064129,...,0,0,1,10,2,7,42,2,5,1
3,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.000000,1.000000,0.522907,0.057606,...,1,1,1,3,27,15,22,1,31,1
5,https://www.globalreporting.org,30,www.globalreporting.org,23,0,org,100.000000,1.000000,0.079963,0.060614,...,0,0,1,35,1,11,86,0,14,1
6,https://www.saffronart.com,25,www.saffronart.com,18,0,com,100.000000,1.000000,0.522907,0.063549,...,0,0,1,32,4,14,44,2,17,1
7,https://www.nerdscandy.com,25,www.nerdscandy.com,18,0,com,100.000000,1.000000,0.522907,0.060486,...,0,0,1,24,2,22,36,0,15,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235790,https://www.skincareliving.com,29,www.skincareliving.com,22,0,com,100.000000,1.000000,0.522907,0.058739,...,1,0,1,51,7,21,187,2,191,1
235791,https://www.winchester.gov.uk,28,www.winchester.gov.uk,21,0,uk,100.000000,0.785714,0.028555,0.053834,...,1,0,0,50,1,7,88,0,31,1
235792,https://www.nononsensedesign.be,30,www.nononsensedesign.be,23,0,be,100.000000,1.000000,0.003319,0.063093,...,0,0,1,27,10,30,58,2,67,1
235793,https://patient-cell-40f5.updatedlogmylogin.wo...,55,patient-cell-40f5.updatedlogmylogin.workers.dev,47,0,dev,28.157537,0.465116,0.000961,0.050211,...,0,0,0,0,0,3,0,0,0,0
235794,https://www.alternativefinland.com,33,www.alternativefinland.com,26,0,com,100.000000,1.000000,0.522907,0.060596,...,0,0,1,21,6,18,256,0,261,1

In [36]:
df.drop(columns=col_to_delete, inplace=True)

In [37]:
df.head()

,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
2,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,0.064129,...,0,0,1,10,2,7,42,2,5,1
3,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,0.057606,...,1,1,1,3,27,15,22,1,31,1
5,https://www.globalreporting.org,30,www.globalreporting.org,23,0,org,100.0,1.000000,0.079963,0.060614,...,0,0,1,35,1,11,86,0,14,1
6,https://www.saffronart.com,25,www.saffronart.com,18,0,com,100.0,1.000000,0.522907,0.063549,...,0,0,1,32,4,14,44,2,17,1
7,https://www.nerdscandy.com,25,www.nerdscandy.com,18,0,com,100.0,1.000000,0.522907,0.060486,...,0,0,1,24,2,22,36,0,15,1

# 1.5 Exploring duplicates

In [39]:
df.duplicated().sum()

0

In [40]:
df.duplicated('URL').sum()

425

In [41]:
df.duplicated('Domain').sum()

15709

In [42]:
df.duplicated('Title').sum()

37920

In [43]:
df[['URL', 'Title']]

,URL,Title
2,https://www.voicefmradio.co.uk,voice fm southampton
3,https://www.sfnmjournal.com,home page: seminars in fetal and neonatal medi...
5,https://www.globalreporting.org,gri - home
6,https://www.saffronart.com,0
7,https://www.nerdscandy.com,nerds candy
...,...,...
235790,https://www.skincareliving.com,skincareliving
235791,https://www.winchester.gov.uk,winchestergov
235792,https://www.nononsensedesign.be,nononsensedesign
235793,https://patient-cell-40f5.updatedlogmylogin.wo...,patient-cell-40f5updatedlogmyloginworkers
235794,https://www.alternativefinland.com,alternativefinland

# 1.5.1 URL

In [45]:
df_url_dup = df[df.duplicated('URL', keep=False)]

In [46]:
# Check which features differ among duplicated URLs
diff_features = df_url_dup.groupby('URL').agg(lambda x: x.nunique() > 1)

# Identify columns with differences
columns_with_diff = diff_features.columns[diff_features.any()]
print("Columns with differences among duplicated URLs:", columns_with_diff)

# Show the differing values for these columns
for column in columns_with_diff:
    print(f"Differences in column '{column}':")
    print(df_url_dup.groupby('URL')[column].apply(list))

Columns with differences among duplicated URLs: Index(['URLLength', 'URLSimilarityIndex', 'URLCharProb', 'ObfuscationRatio',
       'NoOfLettersInURL', 'LetterRatioInURL', 'NoOfDegitsInURL',
       'DegitRatioInURL', 'NoOfOtherSpecialCharsInURL',
       'SpacialCharRatioInURL', 'LineOfCode', 'LargestLineLength', 'HasTitle',
       'Title', 'DomainTitleMatchScore', 'URLTitleMatchScore', 'HasFavicon',
       'Robots', 'IsResponsive', 'NoOfURLRedirect', 'HasDescription',
       'NoOfPopup', 'HasSubmitButton', 'HasHiddenFields', 'HasPasswordField',
       'Bank', 'Pay', 'HasCopyrightInfo', 'NoOfImage', 'NoOfCSS', 'NoOfJS',
       'NoOfSelfRef', 'NoOfEmptyRef', 'NoOfExternalRef'],
      dtype='object')
Differences in column 'URLLength':
URL
http://2f3a.reicrut-chat.workers.dev/                              [36, 37]
http://34.149.138.117/                                             [22, 21]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index4.html    [62, 63]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index8.html    [62, 63]
http://91.239.125.28/postchs/sms.php                               [36, 35]
                                                                     ...
https://yahoo-102275-107804.weeblysite.com/                        [42, 43]
https://yahoo-103138-105991.weeblysite.com/                        [42, 43]
https://yahoo-109157.weeblysite.com/                               [35, 36]
https://yasssouadjanclecles.web.app/                               [36, 35]
https://yellow-river-189b.lhziiz35.workers.dev/                    [46, 47]
Name: URLLength, Length: 425, dtype: object
Differences in column 'URLSimilarityIndex':
URL
http://2f3a.reicrut-chat.workers.dev/                              [27.90328973, 27.90328973]
http://34.149.138.117/                                             [38.23129252, 38.23129252]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index4.html    [27.44249015, 27.44249015]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index8.html    [27.44249015, 27.44249015]
http://91.239.125.28/postchs/sms.php                               [24.18840815, 24.18840815]
                                                                              ...
https://yahoo-102275-107804.weeblysite.com/                        [35.30400395, 35.30400395]
https://yahoo-103138-105991.weeblysite.com/                        [35.30400395, 35.30400395]
https://yahoo-109157.weeblysite.com/                               [54.30139134, 54.30139134]
https://yasssouadjanclecles.web.app/                               [34.39153439, 34.39153439]
https://yellow-river-189b.lhziiz35.workers.dev/                      [29.7322253, 29.7322253]
Name: URLSimilarityIndex, Length: 425, dtype: object
Differences in column 'URLCharProb':
URL
http://2f3a.reicrut-chat.workers.dev/                              [0.051950219, 0.051950219]
http://34.149.138.117/                                             [0.001404235, 0.001404235]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index4.html     [0.03948702, 0.039556186]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index8.html    [0.039481973, 0.039551243]
http://91.239.125.28/postchs/sms.php                               [0.028346783, 0.028500677]
                                                                              ...
https://yahoo-102275-107804.weeblysite.com/                        [0.037026803, 0.037026803]
https://yahoo-103138-105991.weeblysite.com/                        [0.037025474, 0.037025474]
https://yahoo-109157.weeblysite.com/                                 [0.04590044, 0.04590044]
https://yasssouadjanclecles.web.app/                               [0.054935995, 0.054935995]
https://yellow-river-189b.lhziiz35.workers.dev/                    [0.040933648, 0.040933648]
Name: URLCharProb, Length: 425, dtype: object
Differences in column 'ObfuscationRatio':
URL
http://2f3a.reicrut-chat.workers.dev/                              [0.0, 0.0]
http://34.149.138.117/                                             [0.0, 0.0]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index4.html    [0.0, 0.0]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index8.html    [0.0, 0.0]
http://91.239.125.28/postchs/sms.php                               [0.0, 0.0]
                                                                      ...
https://yahoo-102275-107804.weeblysite.com/                        [0.0, 0.0]
https://yahoo-103138-105991.weeblysite.com/                        [0.0, 0.0]
https://yahoo-109157.weeblysite.com/                               [0.0, 0.0]
https://yasssouadjanclecles.web.app/                               [0.0, 0.0]
https://yellow-river-189b.lhziiz35.workers.dev/                    [0.0, 0.0]
Name: ObfuscationRatio, Length: 425, dtype: object
Differences in column 'NoOfLettersInURL':
URL
http://2f3a.reicrut-chat.workers.dev/                              [23, 23]
http://34.149.138.117/                                               [0, 0]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index4.html    [41, 42]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index8.html    [41, 42]
http://91.239.125.28/postchs/sms.php                               [13, 12]
                                                                     ...
https://yahoo-102275-107804.weeblysite.com/                        [18, 18]
https://yahoo-103138-105991.weeblysite.com/                        [18, 18]
https://yahoo-109157.weeblysite.com/                               [18, 18]
https://yasssouadjanclecles.web.app/                               [25, 25]
https://yellow-river-189b.lhziiz35.workers.dev/                    [28, 28]
Name: NoOfLettersInURL, Length: 425, dtype: object
Differences in column 'LetterRatioInURL':
URL
http://2f3a.reicrut-chat.workers.dev/                              [0.639, 0.622]
http://34.149.138.117/                                                 [0.0, 0.0]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index4.html    [0.661, 0.667]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index8.html    [0.661, 0.667]
http://91.239.125.28/postchs/sms.php                               [0.361, 0.343]
                                                                        ...
https://yahoo-102275-107804.weeblysite.com/                        [0.429, 0.419]
https://yahoo-103138-105991.weeblysite.com/                        [0.429, 0.419]
https://yahoo-109157.weeblysite.com/                                 [0.514, 0.5]
https://yasssouadjanclecles.web.app/                               [0.694, 0.714]
https://yellow-river-189b.lhziiz35.workers.dev/                    [0.609, 0.596]
Name: LetterRatioInURL, Length: 425, dtype: object
Differences in column 'NoOfDegitsInURL':
URL
http://2f3a.reicrut-chat.workers.dev/                                [2, 2]
http://34.149.138.117/                                             [11, 11]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index4.html      [7, 7]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index8.html      [7, 7]
http://91.239.125.28/postchs/sms.php                               [10, 10]
                                                                     ...
https://yahoo-102275-107804.weeblysite.com/                        [12, 12]
https://yahoo-103138-105991.weeblysite.com/                        [12, 12]
https://yahoo-109157.weeblysite.com/                                 [6, 6]
https://yasssouadjanclecles.web.app/                                 [0, 0]
https://yellow-river-189b.lhziiz35.workers.dev/                      [5, 5]
Name: NoOfDegitsInURL, Length: 425, dtype: object
Differences in column 'DegitRatioInURL':
URL
http://2f3a.reicrut-chat.workers.dev/                              [0.056, 0.054]
http://34.149.138.117/                                               [0.5, 0.524]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index4.html    [0.113, 0.111]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index8.html    [0.113, 0.111]
http://91.239.125.28/postchs/sms.php                               [0.278, 0.286]
                                                                        ...
https://yahoo-102275-107804.weeblysite.com/                        [0.286, 0.279]
https://yahoo-103138-105991.weeblysite.com/                        [0.286, 0.279]
https://yahoo-109157.weeblysite.com/                               [0.171, 0.167]
https://yasssouadjanclecles.web.app/                                   [0.0, 0.0]
https://yellow-river-189b.lhziiz35.workers.dev/                    [0.109, 0.106]
Name: DegitRatioInURL, Length: 425, dtype: object
Differences in column 'NoOfOtherSpecialCharsInURL':
URL
http://2f3a.reicrut-chat.workers.dev/                              [4, 5]
http://34.149.138.117/                                             [4, 3]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index4.html    [7, 7]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index8.html    [7, 7]
http://91.239.125.28/postchs/sms.php                               [6, 6]
                                                                    ...
https://yahoo-102275-107804.weeblysite.com/                        [4, 5]
https://yahoo-103138-105991.weeblysite.com/                        [4, 5]
https://yahoo-109157.weeblysite.com/                               [3, 4]
https://yasssouadjanclecles.web.app/                               [3, 2]
https://yellow-river-189b.lhziiz35.workers.dev/                    [5, 6]
Name: NoOfOtherSpecialCharsInURL, Length: 425, dtype: object
Differences in column 'SpacialCharRatioInURL':
URL
http://2f3a.reicrut-chat.workers.dev/                              [0.111, 0.135]
http://34.149.138.117/                                             [0.182, 0.143]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index4.html    [0.113, 0.111]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index8.html    [0.113, 0.111]
http://91.239.125.28/postchs/sms.php                               [0.167, 0.171]
                                                                        ...
https://yahoo-102275-107804.weeblysite.com/                        [0.095, 0.116]
https://yahoo-103138-105991.weeblysite.com/                        [0.095, 0.116]
https://yahoo-109157.weeblysite.com/                               [0.086, 0.111]
https://yasssouadjanclecles.web.app/                               [0.083, 0.057]
https://yellow-river-189b.lhziiz35.workers.dev/                    [0.109, 0.128]
Name: SpacialCharRatioInURL, Length: 425, dtype: object
Differences in column 'LineOfCode':
URL
http://2f3a.reicrut-chat.workers.dev/                                  [6, 6]
http://34.149.138.117/                                             [716, 718]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index4.html      [73, 73]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index8.html      [73, 73]
http://91.239.125.28/postchs/sms.php                               [108, 108]
                                                                      ...
https://yahoo-102275-107804.weeblysite.com/                          [68, 68]
https://yahoo-103138-105991.weeblysite.com/                          [68, 68]
https://yahoo-109157.weeblysite.com/                                 [68, 68]
https://yasssouadjanclecles.web.app/                               [108, 108]
https://yellow-river-189b.lhziiz35.workers.dev/                      [45, 45]
Name: LineOfCode, Length: 425, dtype: object
Differences in column 'LargestLineLength':
URL
http://2f3a.reicrut-chat.workers.dev/                                  [84248, 84248]
http://34.149.138.117/                                                 [33721, 36376]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index4.html          [7884, 7884]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index8.html          [7884, 7884]
http://91.239.125.28/postchs/sms.php                                       [240, 240]
                                                                          ...
https://yahoo-102275-107804.weeblysite.com/                                  [80, 80]
https://yahoo-103138-105991.weeblysite.com/                                  [80, 80]
https://yahoo-109157.weeblysite.com/                                         [80, 80]
https://yasssouadjanclecles.web.app/                                     [8125, 8125]
https://yellow-river-189b.lhziiz35.workers.dev/                    [3591544, 3591544]
Name: LargestLineLength, Length: 425, dtype: object
Differences in column 'HasTitle':
URL
http://2f3a.reicrut-chat.workers.dev/                              [0, 0]
http://34.149.138.117/                                             [1, 1]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index4.html    [1, 1]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index8.html    [1, 1]
http://91.239.125.28/postchs/sms.php                               [1, 1]
                                                                    ...
https://yahoo-102275-107804.weeblysite.com/                        [1, 1]
https://yahoo-103138-105991.weeblysite.com/                        [1, 1]
https://yahoo-109157.weeblysite.com/                               [1, 1]
https://yasssouadjanclecles.web.app/                               [1, 1]
https://yellow-river-189b.lhziiz35.workers.dev/                    [1, 1]
Name: HasTitle, Length: 425, dtype: object
Differences in column 'Title':
URL
http://2f3a.reicrut-chat.workers.dev/                                                                         [0, 0]
http://34.149.138.117/                                                                          [34149138, 34149138]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index4.html    [595221selcdnqwerty-ohdhdjejnnad-najahhyindex4...
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index8.html    [595221selcdnqwerty-ohdhdjejnnad-najahhyindex8...
http://91.239.125.28/postchs/sms.php                                   [91239125postchssmsphp, 91239125postchssmsph]
                                                                                         ...
https://yahoo-102275-107804.weeblysite.com/                        [yahoo-102275-107804weeblysite, yahoo-102275-1...
https://yahoo-103138-105991.weeblysite.com/                        [yahoo-103138-105991weeblysite, yahoo-103138-1...
https://yahoo-109157.weeblysite.com/                                [yahoo-109157weeblysite, yahoo-109157weeblysite]
https://yasssouadjanclecles.web.app/                                [yasssouadjancleclesweb, yasssouadjancleclesweb]
https://yellow-river-189b.lhziiz35.workers.dev/                    [yellow-river-189blhziiz35workers, yellow-rive...
Name: Title, Length: 425, dtype: object
Differences in column 'DomainTitleMatchScore':
URL
http://2f3a.reicrut-chat.workers.dev/                              [0.0, 0.0]
http://34.149.138.117/                                             [0.0, 0.0]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index4.html    [0.0, 0.0]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index8.html    [0.0, 0.0]
http://91.239.125.28/postchs/sms.php                               [0.0, 0.0]
                                                                      ...
https://yahoo-102275-107804.weeblysite.com/                        [0.0, 0.0]
https://yahoo-103138-105991.weeblysite.com/                        [0.0, 0.0]
https://yahoo-109157.weeblysite.com/                               [0.0, 0.0]
https://yasssouadjanclecles.web.app/                               [0.0, 0.0]
https://yellow-river-189b.lhziiz35.workers.dev/                    [0.0, 0.0]
Name: DomainTitleMatchScore, Length: 425, dtype: object
Differences in column 'URLTitleMatchScore':
URL
http://2f3a.reicrut-chat.workers.dev/                              [0.0, 0.0]
http://34.149.138.117/                                             [0.0, 0.0]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index4.html    [0.0, 0.0]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index8.html    [0.0, 0.0]
http://91.239.125.28/postchs/sms.php                               [0.0, 0.0]
                                                                      ...
https://yahoo-102275-107804.weeblysite.com/                        [0.0, 0.0]
https://yahoo-103138-105991.weeblysite.com/                        [0.0, 0.0]
https://yahoo-109157.weeblysite.com/                               [0.0, 0.0]
https://yasssouadjanclecles.web.app/                               [0.0, 0.0]
https://yellow-river-189b.lhziiz35.workers.dev/                    [0.0, 0.0]
Name: URLTitleMatchScore, Length: 425, dtype: object
Differences in column 'HasFavicon':
URL
http://2f3a.reicrut-chat.workers.dev/                              [0, 0]
http://34.149.138.117/                                             [0, 0]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index4.html    [0, 0]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index8.html    [0, 0]
http://91.239.125.28/postchs/sms.php                               [0, 0]
                                                                    ...
https://yahoo-102275-107804.weeblysite.com/                        [0, 0]
https://yahoo-103138-105991.weeblysite.com/                        [0, 0]
https://yahoo-109157.weeblysite.com/                               [0, 0]
https://yasssouadjanclecles.web.app/                               [0, 0]
https://yellow-river-189b.lhziiz35.workers.dev/                    [0, 0]
Name: HasFavicon, Length: 425, dtype: object
Differences in column 'Robots':
URL
http://2f3a.reicrut-chat.workers.dev/                              [0, 0]
http://34.149.138.117/                                             [0, 0]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index4.html    [0, 0]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index8.html    [0, 0]
http://91.239.125.28/postchs/sms.php                               [1, 1]
                                                                    ...
https://yahoo-102275-107804.weeblysite.com/                        [0, 0]
https://yahoo-103138-105991.weeblysite.com/                        [0, 0]
https://yahoo-109157.weeblysite.com/                               [0, 0]
https://yasssouadjanclecles.web.app/                               [0, 0]
https://yellow-river-189b.lhziiz35.workers.dev/                    [1, 1]
Name: Robots, Length: 425, dtype: object
Differences in column 'IsResponsive':
URL
http://2f3a.reicrut-chat.workers.dev/                              [0, 0]
http://34.149.138.117/                                             [1, 1]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index4.html    [1, 1]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index8.html    [1, 1]
http://91.239.125.28/postchs/sms.php                               [1, 1]
                                                                    ...
https://yahoo-102275-107804.weeblysite.com/                        [0, 0]
https://yahoo-103138-105991.weeblysite.com/                        [0, 0]
https://yahoo-109157.weeblysite.com/                               [0, 0]
https://yasssouadjanclecles.web.app/                               [1, 1]
https://yellow-river-189b.lhziiz35.workers.dev/                    [1, 1]
Name: IsResponsive, Length: 425, dtype: object
Differences in column 'NoOfURLRedirect':
URL
http://2f3a.reicrut-chat.workers.dev/                              [0, 0]
http://34.149.138.117/                                             [0, 0]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index4.html    [0, 0]
http://595221.selcdn.ru/qwerty-ohdhdjejnnad-najahhy/index8.html    [0, 0]
http://91.239.125.28/postchs/sms.php                               [0, 0]
                                                                    ...
https://yahoo-102275-107804.weeblysite.com/                        [0, 0]

The duplicated urls have differnt values for the same features, which is quite unusual. Without further studying the features we can not safely drop the duplicates. The duplicated values will be handle properly in the exploratory data analysis phase.

In [82]:
df.to_csv('../data/interim/partial_cleaned.csv')