# 1.1 Imports

In [2]:
import pandas as pd
import numpy as np
import re
import requests
from collections import Counter

# 1.2 Load the data

In [4]:
df = pd.read_csv('../data/raw/new_data_urls.csv')
df.head()

                                       url  status
0  0000111servicehelpdesk.godaddysites.com       0
1     000011accesswebform.godaddysites.com       0
2                             00003.online       0
3      0009servicedeskowa.godaddysites.com       0
4                     000n38p.wcomhost.com       0

# 1.3 Dataset overview

In [6]:
df.loc[670137, :]

url       ?
status    0
Name: 670137, dtype: object

In [7]:
df.drop(index=670137, inplace=True)

In [8]:
df.describe()

              status
count  822009.000000
mean        0.519493
std         0.499620
min         0.000000
25%         0.000000
50%         1.000000
75%         1.000000
max         1.000000

In [9]:
df.dtypes

url       object
status     int64
dtype: object

In [10]:
df.isnull().sum()

url       0
status    0
dtype: int64

In [11]:
df.columns

Index(['url', 'status'], dtype='object')

In [12]:
df.shape

(822009, 2)

# 1.4 Exploring for non-ASCII characters

# 1.4.1 URL

In [15]:
def contains_foreign_characters(url):
    '''A function to find out urls with non-ASCII characters'''
    return bool(re.search(r'[^\x00-\x7F]', url))

In [16]:
df['url_contains_foreign'] = df['url'].apply(contains_foreign_characters)

In [17]:
df[df['url_contains_foreign'] == True]

,url,status,url_contains_foreign
28801,http://email302.com/l/5fc15ea15e66c082e33c48ba...,0,True
29659,http://email302.com/l/5fc15ea15e66c082e33c48ba...,0,True
29742,http://u1146016e85.ha004.t.justns.ru/sociﾃｩtﾃｩ...,0,True
30045,http://u10955164a4.ha004.t.justns.ru/sociﾃｩtﾃｩ...,0,True
30311,http://email302.com/l/5fc15ea15e66c082e33c48ba...,0,True
...,...,...,...
678980,copy.com/s8w9tqqzVDaXIkcR/הריגתו של קצין ביטחו...,0,True
679836,venezuela365.com/wp-content/uploads/2014/10/ti...,0,True
679852,www.hjclub.info/bbs/uploadfiles/45/ca-bundle.exe’,0,True
749894,http://email302.com/l/5fc15ea15e66c082e33c48ba...,0,True
749895,http://email302.com/l/5fc15ea15e66c082e33c48ba...,0,True

There are 425 urls that contains non-ASCII characters. We can drop these rows as their percentage is negligible, 0.05%.

# Dropping the urls containing foreign characters

In [20]:
df = df[~df['url_contains_foreign'] == True]

In [21]:
df[df['url_contains_foreign'] == True]

Empty DataFrame
Columns: [url, status, url_contains_foreign]
Index: []

In [22]:
df.isnull().sum()

url                     0
status                  0
url_contains_foreign    0
dtype: int64

In [23]:
df.drop(columns='url_contains_foreign', inplace=True)

In [24]:
df.head()

                                       url  status
0  0000111servicehelpdesk.godaddysites.com       0
1     000011accesswebform.godaddysites.com       0
2                             00003.online       0
3      0009servicedeskowa.godaddysites.com       0
4                     000n38p.wcomhost.com       0

# 1.5 Exploring duplicates

In [26]:
df.duplicated().sum()

13967

Duplicate rows are very few in number, we need to drop them.

In [28]:
df.drop_duplicates(inplace=True)

In [29]:
df.duplicated().sum()

0

Finding URLs that start with characters other than numbers or letters

In [31]:
df[df['url'].str.match(r'^[^a-zA-Z0-9]')]

                                                      url  status
191868  -https://www.cinemaximum.com.tr/cakallarla-dan...       1
192050  'motors.shop.ebay.com-cars-trucks-724527.jnq3....       0
192064  'www.gestion-des-impayes.com/visuel.php?param=...       0
192141  'nicolecustodio.com.br/paypal\%20us/webscr.htm...       0
192227  'beforenanny911.com/auto/my-themes/file/proper...       0
...                                                   ...     ...
680466   intent.nofrillspace.com/users/web11_focus/380...       0
680468   mister.nofrillspace.com/users/web8_dice/3791/...       0
684998                                    69.162.100.198/       0
685257                                babicz123.ddns.net/       0
699156                             highpowerresources.com       0

[3916 rows x 2 columns]

Finding URLs that are enclosed in either single quotes (') or double quotes (")

In [33]:
df[df['url'].str.contains(r"^['\"].*['\"]$", na=False)]

                                                      url  status
192050  'motors.shop.ebay.com-cars-trucks-724527.jnq3....       0
192064  'www.gestion-des-impayes.com/visuel.php?param=...       0
192141  'nicolecustodio.com.br/paypal\%20us/webscr.htm...       0
192227  'beforenanny911.com/auto/my-themes/file/proper...       0
192234  'www.edyshsdf32.hut4.ru/Redirecionamento.html?...       0
...                                                   ...     ...
287613  'www.fileplanet.com/100541/0/section/Marc-Ecko...       1
287615  'en.wikipedia.org/wiki/Marc_Ecko\'s_Getting_Up...       1
287928  'www.armchairempire.com/Reviews/PC\%20Games/al...       1
287932  'www.mobygames.com/game_group/sheet/gameGroupI...       1
287959  'www.armchairempire.com/Reviews/PC\%20Games/un...       1

[3900 rows x 2 columns]

Removing the quotes and special characters in front of the urls

In [35]:
df['url'] = df['url'].str.replace(r"^['\"^\W]+", '', regex=True)

In [36]:
df[df['url'].str.match(r'^[^a-zA-Z0-9]')]

Empty DataFrame
Columns: [url, status]
Index: []

In [37]:
df[df['url'].str.contains(r"^['\"].*['\"]$", na=False)]

Empty DataFrame
Columns: [url, status]
Index: []

In [38]:
df.isnull().sum()

url       0
status    0
dtype: int64

In [39]:
def remove_spaces(url):
    return url.replace(' ', '')  # Replaces all spaces with an empty string

In [40]:
df['url'] = df['url'].apply(remove_spaces)

In [41]:
def has_space(url):
    return ' ' in url

In [42]:
df[(df['url'].apply(has_space)) & (df.status == 0)]

Empty DataFrame
Columns: [url, status]
Index: []

In [43]:
df[(df['url'].apply(has_space)) & (df.status == 1)]

Empty DataFrame
Columns: [url, status]
Index: []

In [44]:
df.reset_index(drop=True, inplace=True)

In [45]:
df.to_csv('../data/processed/url_new_cleaned.csv')